---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-java-geyser-config
  labels:
    role: service-config
    app: mc-java-geyser
data:
  UID: "1001"
  GID: "1001"
  EULA: "TRUE" # Must accept EULA to use this minecraft server
  TYPE: "PAPER"
  VERSION: "1.21.11"
  MEMORY: "4096M"
  MAX_PLAYERS: "10"
  MOTD: "Anton MC Geyser"
  USE_AIKAR_FLAGS: "true"
  USE_MEOWICE_FLAGS: "true"
  TZ: "Europe/Warsaw"
  DIFFICULTY: "2"
  LEVEL: "Anton MC"
  LEVEL_TYPE: "amplified"
  ONLINE_MODE: "true"
  ENABLE_WHITELIST: "true"
  ENABLE_ROLLING_LOGS: "true"
  LOG_TIMESTAMP: "true"
  LOG_IPS: "false"
  PLUGINS: |-
    https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
    https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    https://github.com/ViaVersion/ViaVersion/releases/download/5.7.1/ViaVersion-5.7.1.jar