---
apiVersion: v1
kind: Service
metadata:
  name: mc-java-geyser-service
spec:
  selector:
    app: mc-java-geyser
  ports:
    - name: minecraft-java
      protocol: TCP
      port: 25565 
      nodePort: 30001
    - name: minecraft-bedrock
      protocol: UDP
      port: 19132
      nodePort: 30002
  type: NodePort
