---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-java-aether-config
  labels:
    role: service-config
    app: mc-java-aether
data:
  UID: "1001"
  GID: "1001"
  EULA: "TRUE" # Must accept EULA to use this minecraft server
  TYPE: "MODRINTH"
  VERSION: "1.21.1"
  MODRINTH_MODPACK: "https://modrinth.com/modpack/aetherplus"
  MODRINTH_VERSION: "5"
  MEMORY: "4096M"
  MAX_PLAYERS: "10"
  MOTD: "Anton MC Aether Plus"
  USE_AIKAR_FLAGS: "true"
  USE_MEOWICE_FLAGS: "true"
  TZ: "Europe/Warsaw"
  DIFFICULTY: "2"
  LEVEL: "Anton MC"
  LEVEL_TYPE: "amplified"
  ENABLE_WHITELIST: "true"
  ENABLE_ROLLING_LOGS: "true"
  LOG_TIMESTAMP: "true"
  LOG_IPS: "false"