---
apiVersion: v1
kind: Service
metadata:
  name: mc-java-aether-service
spec:
  selector:
    app: mc-java-aether
  ports:
    - protocol: TCP
      port: 25565 
      nodePort: 30000
  type: NodePort
