apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anton-docs-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - anton.golebiowski.dev
      secretName: letsencrypt-prod-anton-tls-secret
  rules:
    - host: anton.golebiowski.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anton-docs-service
                port:
                  number: 8080
