---
apiVersion: v1
kind: Service
metadata:
  name: teamspeak-6-service
spec:
  selector:
    app: teamspeak-6
  ports:
    - name: teamspeak-6-voice
      protocol: UDP
      port: 9987
      nodePort: 31000
    - name: teamspeak-6-file-transfer
      protocol: TCP
      port: 30033
      nodePort: 30033
    #- name: teamspeak-6-web-query
    #  protocol: TCP
    #  port: 10080
    #  nodePort: 30003
  type: NodePort